[settings]
experimental = true
disable_backends = ["asdf", "vfox"]
idiomatic_version_file_enable_tools = ["node"]

[settings.pipx]
uvx = true

[tools]
bun = "latest"
"cargo:similarity-ts" = "latest"
node = "latest"
"npm:@aikidosec/safe-chain" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:editprompt" = "latest"
"npm:mdjanai" = "latest"
"npm:pnpm" = "latest"
"npm:sdd-mcp" = "latest"
"npm:vde-layout" = "latest"
"npm:vde-notifier" = "latest"
"npm:yarn" = "latest"
python = "3.14"
uv = "latest"
